name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright
        playwright install

    - name: Deploy to Render
      uses: render-examples/deploy@v1
      with:
        api_key: ${{ secrets.RENDER_API_KEY }}
        service_id: ${{ secrets.RENDER_SERVICE_ID }}

